### PR TITLE
Add metadata Rubygems

### LINKED ISSUE #8: Add rubygems metadata
This Issue is about adding [rubygems metadata](https://guides.rubygems.org/specification-reference/#metadata) to link to important parts of this repo in the Rubygems.org website.

Add as much metadata as you find to be useful!

```ruby
{
  "bug_tracker_uri"   => "https://github.com/eco-rb/bundler-ecology/issues/",
  "changelog_uri"     => "https://github.com/eco-rb/bundler-ecology/blob/v#{spec.version}/CHANGELOG.md",
}
```

### PR DESCRIPTION
**Pull request by luizpicolo**
Added simple metadata to source code.

Fixes #8

### CODE REVIEW

**Comment by olleolleolle** [comment]
Can we have the change log in there, too?

**Comment by luizpicolo** [comment]
Yes, but we can handle this in another commit. what do you think?

**Comment by v-kolesnikov** [comment]
I think it is no needed to make many PR's. This issue is about adding metadata, so we should add entire metadata in a single commit.

**Comment by olleolleolle** [comment]
Perhaps these two links can come, too?

```ruby
{
  "bug_tracker_uri"   => "https://github.com/eco-rb/bundler-ecology/issues/",
  "changelog_uri"     => "https://github.com/eco-rb/bundler-ecology/blob/v#{spec.version}/CHANGELOG.md"
}
```

**Comment by olleolleolle** [comment]
Thanks, this was committed and merged in #12 🚀

**Pull request closed without merging**
